#! /bin/sh
# github.com/mmskv
# 2021

bspc monitor -d 主要 付帯 備蓄 セブン  #Dev Dev Browse Browse Game Game Net Net Misc
bspc config border_width         3
bspc config window_gap           15
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focused_border_color \#373B41
bspc config normal_border_color  \#282A2E
bspc config border_radius        10
bspc config pointer_modifier     mod4
bspc config pointer_action1      move
bspc config pointer_action2      resize_side
bspc config pointer_action3      resize_corner
bspc config automatic_scheme     spiral
bspc rule -a Gimp desktop='^4' state=floating follow=on

# Autostart mostly copied from my i3 config

killall sxhkd;
sxhkd  &
# .local/bin/wal -R  &
killall unclutter; 
unclutter -grab -idle 3  &
bash /home/overaid/.screenlayout/first.sh  &
pgrep bspswallow || bspswallow &
setxkbmap -layout us,ru -option grp:alt_space_toggle -option caps:escape  &
# Safe start picom
/home/overaid/usr/launch-compton.sh  &
# Safe start polybar
/home/nekohacker/.config/polybar/launch.sh &
# Set button repeat speed on hold
xset r rate 380 35  &
# Start redshift
redshift -b 1:0.9 -t 6500:5500 -c ~/.config/redshift.conf  &
# Fill wallpaper
feh --bg-fill /warehouse/Wallpapers/darkAnimeUltrawide/tsundere.png &
# Bind Shift_R and Shift_L to matching parenthesis
killall xcape -9;
xcape -e 'Shift_L=parenleft;Shift_R=parenright'  &
# Bind Wacom Tablet to main display
xsetwacom set "Wacom One by Wacom M Pen stylus" MapToOutput HEAD-0   &
xrdb -merge ~/.Xresources &
# Start xbindkeys
xbindkeys &
