#! /bin/sh
# github.com/mmskv
# 2021

DP=$(xrandr --listactivemonitors | tail -n2 | awk '{ print $4}' | grep DP);

bspc monitor $DP -d 主要 付帯 備蓄 セブン  #Dev Dev Browse Browse Game Game Net Net Misc
bspc config border_width            2
bspc config border_radius           15
bspc config window_gap              10
bspc config split_ratio             0.61
bspc config borderless_monocle      true
bspc config gapless_monocle         false
bspc config pointer_follows_monitor true
bspc config focused_border_color    \#373B41
bspc config normal_border_color     \#282A2E
bspc config presel_feedback_color   \#8C9440
bspc config pointer_modifier        mod4
bspc config pointer_action1         move
bspc config pointer_action2         resize_side
bspc config pointer_action3         resize_corner
bspc config automatic_scheme        spiral

bspc rule -a Gimp desktop='^4' state=floating follow=on

$HOME/.screenlayout/first.sh ;
killall sxhkd;
sxhkd  &
killall unclutter; 
unclutter -grab -idle 3  &
pgrep bspswallow || bspswallow  &
setxkbmap -layout us,ru -option grp:alt_space_toggle -option caps:ctrl_modifier  &
# Safe start
$HOME/dotfiles/scripts/launch-compton.sh  &
$HOME/.config/polybar/launch.sh  &
xset r rate 380 35  & # Set button repeat speed
# Fill wallpaper
$HOME/.fehbg  &
# Bind Shift_R and Shift_L to matching parenthesis
killall xcape -9;
xcape -e 'Shift_L=parenleft;Shift_R=parenright'  &
xcape -e 'Caps_Lock=Escape'  &
# Bind Wacom Tablet to main display
xsetwacom set "Wacom One by Wacom M Pen stylus" MapToOutput HEAD-0   &
xrdb -merge $HOME/.Xresources  &
killall redshift -9 && redshift -x && redshift -c $HOME/.config/redshift.conf || redshift -c $HOME/.config/redshift.conf &
xbindkeys  &
gpg-agent --daemon &
