#!/bin/sh

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# Use the "logo" key as the primary modifier
mod="Mod4"

# Touchpad
riverctl input "pointer-1452-640-bcm5974" disable-while-typing enabled
riverctl input "pointer-1452-640-bcm5974" pointer-accel 0.1
riverctl input "pointer-1452-640-bcm5974" accel-profile adaptive
riverctl input "pointer-1452-640-bcm5974" natural-scroll enabled

riverctl map normal $mod Return spawn alacritty
riverctl map normal $mod B spawn firefox
riverctl map normal $mod I spawn telegram-desktop
riverctl map normal $mod Space spawn ~/dotfiles/scripts/dmenu.sh
        

# Mod+Q to close the focused view
riverctl map normal $mod Q close

# Mod+Shift+E to exit river
riverctl map normal $mod+Shift E exit

# Mod+J and Mod+K to focus the next/previous view in the layout stack
riverctl map normal $mod J focus-view next
riverctl map normal $mod K focus-view previous

# Mod+Shift+J and Mod+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal $mod+Shift J swap next
riverctl map normal $mod+Shift K swap previous

# Mod+Return to bump the focused view to the top of the layout stack
riverctl map normal $mod+Shift Return zoom

# Mod+H and Mod+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal $mod H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal $mod L send-layout-cmd rivertile "main-ratio +0.05"

# Mod+Shift+H and Mod+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal $mod+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal $mod+Shift L send-layout-cmd rivertile "main-count -1"

# Mod+Alt+{H,J,K,L} to move views
riverctl map normal $mod+Mod1 H move left 100
riverctl map normal $mod+Mod1 J move down 100
riverctl map normal $mod+Mod1 K move up 100
riverctl map normal $mod+Mod1 L move right 100

# Mod + Left Mouse Button to move views
riverctl map-pointer normal $mod BTN_LEFT move-view

# Mod + Right Mouse Button to resize views
riverctl map-pointer normal $mod BTN_RIGHT resize-view

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Mod+[1-9] to focus tag [0-8]
    riverctl map normal $mod $i set-focused-tags $tags

    # Mod+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal $mod+Shift $i set-view-tags $tags

    # Mod+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal $mod+Control $i toggle-focused-tags $tags

    # Mod+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal $mod+Shift+Control $i toggle-view-tags $tags
done

# Mod+0 to focus all tags
# Mod+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal $mod 0 set-focused-tags $all_tags
riverctl map normal $mod+Shift 0 set-view-tags $all_tags

riverctl map normal $mod+Shift Space toggle-float
riverctl map normal $mod F toggle-fullscreen

# Mod+{Up,Right,Down,Left} to change layout orientation
riverctl map normal $mod Up    send-layout-cmd rivertile "main-location top"
riverctl map normal $mod Right send-layout-cmd rivertile "main-location right"
riverctl map normal $mod Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal $mod Left  send-layout-cmd rivertile "main-location left"

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    riverctl map $mode None XF86AudioRaiseVolume  spawn '~/dotfiles/scripts/change-volume.sh up'
    riverctl map $mode None XF86AudioLowerVolume  spawn '~/dotfiles/scripts/change-volume.sh down'
    riverctl map $mode None XF86AudioMute         spawn '~/dotfiles/scripts/change-volume.sh mute'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brighness with light (https://github.com/haikarainen/light)
    riverctl map $mode None XF86MonBrightnessUp   spawn '~/dotfiles/scripts/brightnessctl.sh up'
    riverctl map $mode None XF86MonBrightnessDown spawn '~/dotfiles/scripts/brightnessctl.sh down'

    # Screenshot
    riverctl map $mode None XF86LaunchA spawn 'killall slurp; grim -g "$(slurp)" - | wl-copy'
    riverctl map $mode None XF86LaunchB spawn 'killall slurp; grim -g "$(slurp)" "~/Downloads/screenshots/Screenshot.png"'
done

# Set background and border color
riverctl border-color-focused 0x777777
riverctl border-color-unfocused 0x33010d

# Set keyboard repeat rate
riverctl set-repeat 35 380

# Make certain views start floating
riverctl float-filter-add app-id float
riverctl float-filter-add title "gimp"
riverctl float-filter-add title "Volume Control"

# Set app-ids and titles of views which should use client side decorations
riverctl csd-filter-add app-id "gedit"

# Set and exec into the default layout generator, rivertile.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile

kanshi -c ~/.config/kanshi.conf &
swaybg -m fill -i ~/dotfiles/wallpapers/spin.jpg &
gsettings set org.gnome.desktop.interface gtk-theme 'Arc-Dark' &
waybar &
swayidle -w \
     timeout 100 'brightnessctl -s & brightnessctl set 5%' \
         resume 'brightnessctl -r &' \
     timeout 150 'swaylock -f -c 000000' \
     timeout 600 'wlopm --off eDP-1' resume 'wlopm --on eDP-1' \
     before-sleep 'swaylock -f -c 000000' &
exec rivertile -view-padding 6 -outer-padding 6 &
source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh
# see https://wiki.archlinux.org/title/GNOME/Keyring#xinitrc
#eval $(/usr/bin/gnome-keyring-daemon --start)
#export SSH_AUTH_SOCK
